# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/indepndent-context.js
#####

SDLC_INDEPNDENT_CONTEXT_JS:=$(DIST)/indepndent-context.js
SDLC_INDEPNDENT_CONTEXT_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(SDLC_INDEPNDENT_CONTEXT_JS)

$(SDLC_INDEPNDENT_CONTEXT_JS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_INDEPNDENT_CONTEXT_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/indepndent-context.js
#####
